export const mockListings = [
    {
        id: "1",
        data: {
            name: "3 Bed / 3 Bath Short Term Rental",
            street: "4324 E Stanford Dr",
            city: "Phoenix",
            state: "AZ",
            zipcode: "85018",
            rent: 7500,
            type: "Leased",
            lineSummary: "3 Beds • 3 Bath • 2,600 sqft • Built in 1950 • Single Family",
            paragraph:
                "Mid-Century Modern 1959 - Behold the epitome of sophistication and style in this beautifully maintained property...",
            lng: -111.9796,
            lat: 33.5032,
            soldPercentage: 30,
            initialSave: "false",

        },
        initialImages: [
            "https://placehold.co/500?text=Main+Property",
            "https://placehold.co/500?text=Image1",
            "https://placehold.co/500?text=Image2",
            "https://placehold.co/500?text=Image3",
            "https://placehold.co/500?text=Image4",
        ],
        addressCoordinates: [{ lng: -111.9796, lat: 33.5032 }],

        ownershipData: {
            blocksOwn: 200,
            paidPrice: 11.52,
            currentPrice: 28.5,
            accountBalance: 10000.0,
            title: "3 Bed / 3 Bath Short Term Rental",
            location: "Miami, FL",
            realType: "SingleFamily",
            imgSrc: "https://placehold.co/200x150?text=ShortTermRental"

        },
        investData: {
            propertyId: 1,
            address: "4324 E Stanford Drive",
            pricePerBlock: 26.5,
            accountB: 100000,
            title: "3 Bed / 3 Bath Short Term Rental",
            location: "4324 E Stanford Dr, Phoenix, AZ 85018",
            realType: "SingleFamily",
            raised: 400000,
            raiseTarget: 900000,
            investment: 100,
            estimate: 835000,
            roi: 7,
            imgSrc: "https://placehold.co/200x150?text=ShortTermRental",
            latitude: 33.5032,
            longitude: -111.9796,
        },
        documents: [
            "Lease Agreement",
            "Blueprints",
            "Mortgage Documents",
            "Compliance Certificates",
            "Lease Agreement",
            "Blueprints",
            "Mortgage Documents",
            "Compliance Certificates",
        ],
        cashAndFinancing: {
            offeringBreakdown: 2000000,
            contractPrice: 1869366,
            cashReserve: 51442,
            improvementCost: 121452,
            dueDiligence: 4609,
            acquisitionFee: 132903,
        },
        locationDetails: {
            neighborhood: "Housing District",
            nearbyFacilities: ["Parks","Schools","Hospitals"],
        },financialDetails: {
            details: {
                month: "January",
                shares: 7000,
            },
            income: [
                { name: "Rent (Main House)", amount: 7500 },
                { name: "Garage Rental", amount: 200 },
                { name: "Laundry Income", amount: 100 },
            ],
            expenses: [
                { name: "Mortgage (P&I)", amount: 1800 },
                { name: "Maintenance", amount: 150 },
                { name: "Landscaping", amount: 100 },
                { name: "Utilities", amount: 300 },
                { name: "Insurance", amount: 120 },
                { name: "Taxes", amount: 250 },
            ],
        },
        additionalDetails: {
            numberOfUnits: 1,
            squareFootage: 1500,
            yearBuilt: 2005,
            amenities: ['Pool', 'Gym', 'Playground'],
            occupancyRate: 100, 
            capRate: null,
            grossRentalIncome: 24000,
            noi: null,
            propertyValue: 300000,
            propertyType: 'Residential',
            otherType: null,
            yearRenovated: 2020,
            propertyCondition: 'Good',
            parkingSpaces: 2,
            bedrooms: 3,
            bathrooms: 2,
            hasGarage: true,
            hasBasement: false,
            isOccupied: true,
            propertyAmenities: ['Balcony', 'Central Heating'],
            numberOfUnits: 1,
            occupancyRate: 100,
            floors: 2,
            lotSize: 6000,
            zoning: 'Residential',
            topography: 'Flat',
            expectedCompletionDate: null,
            constructionPhase: null,
            estimatedConstructionCost: null,
            permitStatus: null,
            floorCount: null,
            loadingDocks: null,
            specializedEquipment: null,
            numberOfRooms: 8,
            starRating: null,
            footTraffic: null,
        },
        dividendInfo: {
            month: "April",
            collectedRent: 7450,
            managementFee: 100,
            monthlyHoa: 16,
            insurance: 126,
            interestPayment: 500,
            changeInCash: 1708,
            dividend: 715,
            SharesSoldLastMonth: 1400,
            perShare: 0.5,
        },
        developerInfo: {
            name: "Real Estate-Premium Properties",
            listingCount: 14,
            joinedYear: 2020,
        },
    },
    {
        id: "2",
        data: {
            name: "2 Bed / 2 Bath Urban Apartment",
            street: "123 Main St",
            city: "New York",
            state: "NY",
            zipcode: "10001",
            rent: 5000,
            type: "Available",
            lineSummary: "2 Beds • 2 Bath • 1,200 sqft • Built in 2010 • Apartment",
            paragraph:
                "Experience the heart of the city with this modern apartment, offering stunning views and top-notch amenities...",
            lng: -73.9857,
            lat: 40.7484,
            soldPercentage: 30,
            initialSave: "false",
        },
        initialImages: [
            "https://placehold.co/500?text=Main+Property",
            "https://placehold.co/500?text=Image1",
            "https://placehold.co/500?text=Image2",
            "https://placehold.co/500?text=Image3",
            "https://placehold.co/500?text=Image4",
        ],
        addressCoordinates: [{ lng: -73.9857, lat: 40.7484 }],

        ownershipData: {
            blocksOwn: 200,
            paidPrice: 11.52,
            currentPrice: 28.5,
            accountBalance: 10000.0,
            title: "3 Bed / 3 Bath Short Term Rental",
            location: "Miami, FL",
            realType: "SingleFamily",
            imgSrc: "https://placehold.co/200x150?text=ShortTermRental"

        },
        investData: {
            address: "4324 E Stanford Drive",
            pricePerBlock: 26.5,
            accountB: 100000,
            title: "3 Bed / 3 Bath Short Term Rental",
            location: "4324 E Stanford Dr, Phoenix, AZ 85018",
            realType: "SingleFamily",
            raised: 400000,
            raiseTarget: 900000,
            investment: 100,
            estimate: 835000,
            roi: 7,
            imgSrc: "https://placehold.co/200x150?text=ShortTermRental",
            latitude: 33.5032,
            longitude: -111.9796,
        },
        documents: [
            "Lease Agreement",
            "Blueprints",
            "Mortgage Documents",
            "Compliance Certificates",
            "Lease Agreement",
            "Blueprints",
            "Mortgage Documents",
            "Compliance Certificates",
        ],
        cashAndFinancing: {
            offeringBreakdown: 1500000,
            contractPrice: 1400000,
            cashReserve: 30000,
            improvementCost: 90000,
            dueDiligence: 3500,
            acquisitionFee: 100000,
        },
        dividendInfo: {
            month: "May",
            collectedRent: 6200,
            managementFee: 120,
            monthlyHoa: 20,
            insurance: 150,
            interestPayment: 600,
            changeInCash: 2100,
            dividend: 800,
            SharesSoldLastMonth: 1600,
            perShare: 0.6,
        },
        developerInfo: {
            name: "Urban Living Developers",
            listingCount: 20,
            joinedYear: 2018,
        },
    },
    {
        id: "3",
        data: {
            name: "4 Bed / 3 Bath Suburban Home",
            street: "789 Oak Ave",
            city: "San Francisco",
            state: "CA",
            zipcode: "94102",
            rent: 8500,
            type: "Sold",
            lineSummary: "4 Beds • 3 Bath • 3,000 sqft • Built in 1995 • Single Family",
            paragraph:
                "A beautiful family home located in the quiet suburbs, featuring spacious rooms and a large backyard...",
            lng: -122.4194,
            lat: 37.7749,
            soldPercentage: 30,
            initialSave: "false",
        },
        initialImages: [
            "https://placehold.co/500?text=Main+Property",
            "https://placehold.co/500?text=Image1",
            "https://placehold.co/500?text=Image2",
            "https://placehold.co/500?text=Image3",
            "https://placehold.co/500?text=Image4",
        ],
        addressCoordinates: [{ lng: -122.4194, lat: 37.7749 }],

        ownershipData: {
            blocksOwn: 200,
            paidPrice: 11.52,
            currentPrice: 28.5,
            accountBalance: 10000.0,
            title: "3 Bed / 3 Bath Short Term Rental",
            location: "Miami, FL",
            realType: "SingleFamily",
            imgSrc: "https://placehold.co/200x150?text=ShortTermRental"

        },
        investData: {
            address: "4324 E Stanford Drive",
            pricePerBlock: 26.5,
            accountB: 100000,
            title: "3 Bed / 3 Bath Short Term Rental",
            location: "4324 E Stanford Dr, Phoenix, AZ 85018",
            realType: "SingleFamily",
            raised: 400000,
            raiseTarget: 900000,
            investment: 100,
            estimate: 835000,
            roi: 7,
            imgSrc: "https://placehold.co/200x150?text=ShortTermRental",
            latitude: 33.5032,
            longitude: -111.9796,
        },
        documents: [
            "Sales Agreement",
            "Inspection Reports",
            "Property Appraisal",
            "Title Deed",
        ],
        cashAndFinancing: {
            offeringBreakdown: 2500000,
            contractPrice: 2300000,
            cashReserve: 60000,
            improvementCost: 150000,
            dueDiligence: 5500,
            acquisitionFee: 200000,
        },
        dividendInfo: {
            month: "June",
            collectedRent: 9000,
            managementFee: 150,
            monthlyHoa: 25,
            insurance: 180,
            interestPayment: 700,
            changeInCash: 2500,
            dividend: 950,
            SharesSoldLastMonth: 1800,
            perShare: 0.7,
        },
        developerInfo: {
            name: "Suburban Estates LLC",
            listingCount: 10,
            joinedYear: 2015,
        },
    },
];
